version: '3'

services:
  proxy:
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - ENVIRONMENT=production

  frontend:
    environment:
      - NODE_ENV=production

  backend:
    environment:
      - ENVIRONMENT=production
      - DEBUG=0

  # Disable certbot temporarily
  certbot:
    profiles:
      - disabled
