[http.middlewares]
  [http.middlewares.rate-limit]
    [http.middlewares.rate-limit.rateLimit]
      average = 100
      burst = 50
      period = "1m"

  [http.middlewares.secure-headers]
    [http.middlewares.secure-headers.headers]
      browserXssFilter = true
      contentTypeNosniff = true
      frameDeny = true
      stsIncludeSubdomains = true
      stsPreload = true
      stsSeconds = 31536000
      customFrameOptionsValue = "SAMEORIGIN"
      customResponseHeaders = {
        "X-Content-Type-Options" = "nosniff",
        "X-Frame-Options" = "SAMEORIGIN",
        "X-XSS-Protection" = "1; mode=block",
        "Referrer-Policy" = "strict-origin-when-cross-origin"
      }

  [http.middlewares.compress]
    [http.middlewares.compress.compress]

  [http.middlewares.https-redirect]
    [http.middlewares.https-redirect.redirectscheme]
      scheme = "https"
      permanent = true
      
  [http.middlewares.admin-auth]
    [http.middlewares.admin-auth.basicauth]
      users = [
        "admin:$apr1$RlYxCfJI$DU4wcOhx7RAlTEp4ElH0J/"
      ] 